import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { getReport, listReports } from '../lib/api';

export default function ReportsPage() {
  const [selected, setSelected] = useState<string | null>(null);
  const reports = useQuery({ queryKey: ['reports'], queryFn: listReports });
  const detail = useQuery({
    queryKey: ['report-detail', selected],
    queryFn: () => getReport(selected!),
    enabled: Boolean(selected),
  });

  return (
    <div className="page">
      <div className="page-title">
        <div>
          <h1>Reports</h1>
          <p>Browse local Markdown reports generated by Codex-assisted and API analysis flows.</p>
        </div>
      </div>
      <div className="two-column reports-grid">
        <section className="panel">
          <h2>Local reports</h2>
          <table>
            <thead>
              <tr>
                <th>Source</th>
                <th>Title</th>
                <th>Modified</th>
              </tr>
            </thead>
            <tbody>
              {(reports.data ?? []).map((report) => (
                <tr key={report.report_id} onClick={() => setSelected(report.report_id)} className="clickable-row">
                  <td>{report.source}</td>
                  <td>{report.title}</td>
                  <td>{report.modified_at.slice(0, 10)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
        <section className="panel">
          <h2>Report preview</h2>
          {detail.data ? (
            <>
              <p className="path-cell">{detail.data.path}</p>
              <pre className="report-preview">{detail.data.content}</pre>
            </>
          ) : (
            <p className="muted">Select a report to preview it.</p>
          )}
        </section>
      </div>
    </div>
  );
}
